language: c

install:
  - export CC=arm-none-eabi-as
  - arm-none-eabi-as --version
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded && sudo apt-get update
  - sudo apt-get install build-essential gcc-arm-none-eabi git
  - $CC --version
  - echo $PATH
  - export V=1
  - export PYTHON2=python
  - export USE_ESKYLINK=0
  - export CLOAD=0

script: make all

notifications:
  email: false