language: c

before_script:
  - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major/+download/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
  - tar -xf gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-4_9-2014q4/bin

install:
  - ls -lat ./gcc-arm-none-eabi-4_9-2014q4/bin
  - export V=1
  - export PYTHON2=python
  - export USE_ESKYLINK=0
  - export CLOAD=0

script: make all

notifications:
  email: false