#!/bin/bash

# This script sets up a travis-ci VM for compiling our project
# Unfortunately we can't use our regular ubuntu setup script because travis
# uses a much older version of Ubuntu
# NOTE: this must be executed from the root of the repo

export $BUILD_ROOT_DIR=$(pwd)

sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'
sudo apt-get update -qq
sudo apt-get install -y gcc-arm-none-eabi mercurial python2.7 python-usb python-pygame python-qt4 qt4-designer openocd build-essential

echo -e "\nPATH=\$PATH:$BUILD_ROOT_DIR/bin/gcc-arm-none-eabi/bin" >> ./.bashrc
source ./bashrc