#!/usr/bin/env sh

# This script sets up a travis-ci VM for compiling our project
# Unfortunately we can't use our regular ubuntu setup script because travis
# uses a much older version of Ubuntu
# NOTE: this must be executed from the root of the repo

# Enable error reporting to the console
export $BUILD_ROOT_DIR=$(pwd)

sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'
sudo apt-get update -qq
sudo apt-get install -y gcc-arm-none-eabi mercurial python2.7 python-usb python-pygame python-qt4 qt4-designer openocd build-essential

echo -e "\nPATH=\$PATH:$BUILD_ROOT_DIR/bin/gcc-arm-none-eabi/bin" >> ./.bashrc
source ./bashrc

echo "Branch: $TRAVIS_BRANCH"
echo "======================"
echo "Job Number: $TRAVIS_JOB_NUMBER"
echo "Job ID: $TRAVIS_JOB_ID"
echo "Build Number: $TRAVIS_BUILD_NUMBER"
echo "Build ID: $TRAVIS_BUILD_ID"